/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MCViews;

/**
 *
 * @author DELL
 */
public class mainForm extends javax.swing.JFrame {

    public static int empIdM;

    public int getEmpId() {
        return empIdM;
    }

    public void setEmpId(int empId) {
        this.empIdM = empId;
    }
    
    /**
     * Creates new form mainForm
     */
    public mainForm(int empId) {
        initComponents();
        empIdM = empId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        scheduleBtn = new javax.swing.JButton();
        movieBtn = new javax.swing.JButton();
        theaterBtn = new javax.swing.JButton();
        saleBtn = new javax.swing.JButton();
        seatBtn = new javax.swing.JButton();
        storageBtn = new javax.swing.JButton();
        employeeBtn = new javax.swing.JButton();
        reportBtn = new javax.swing.JButton();
        sellProductBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(252, 214, 112));
        setMaximumSize(new java.awt.Dimension(620, 400));
        setMinimumSize(new java.awt.Dimension(620, 400));

        kGradientPanel1.setkEndColor(new java.awt.Color(252, 214, 112));
        kGradientPanel1.setkStartColor(new java.awt.Color(241, 90, 34));
        kGradientPanel1.setMaximumSize(new java.awt.Dimension(620, 400));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(620, 400));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(620, 400));

        scheduleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/scheduleIcon64px.png"))); // NOI18N
        scheduleBtn.setText("Schedule");
        scheduleBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        scheduleBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        scheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleBtnActionPerformed(evt);
            }
        });

        movieBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/movieIcon64px.png"))); // NOI18N
        movieBtn.setText("Movie");
        movieBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        movieBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        movieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieBtnActionPerformed(evt);
            }
        });

        theaterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/theaterIcon64px.png"))); // NOI18N
        theaterBtn.setText("Theater");
        theaterBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        theaterBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        theaterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theaterBtnActionPerformed(evt);
            }
        });

        saleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/transactionIcon64px.png"))); // NOI18N
        saleBtn.setText("Transaction");
        saleBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saleBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleBtnActionPerformed(evt);
            }
        });

        seatBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/seatIcon64px.png"))); // NOI18N
        seatBtn.setText("Seat");
        seatBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seatBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        seatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatBtnActionPerformed(evt);
            }
        });

        storageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/storageIcon64px.png"))); // NOI18N
        storageBtn.setText("Storage");
        storageBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        storageBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        storageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storageBtnActionPerformed(evt);
            }
        });

        employeeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/employeeIcon64px.png"))); // NOI18N
        employeeBtn.setText("Employee");
        employeeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        employeeBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        employeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtnActionPerformed(evt);
            }
        });

        reportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/reportIcon64px.png"))); // NOI18N
        reportBtn.setText("Report");
        reportBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reportBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBtnActionPerformed(evt);
            }
        });

        sellProductBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/sellProductIcon64px.png"))); // NOI18N
        sellProductBtn.setText("Product Sale");
        sellProductBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sellProductBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sellProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellProductBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(sellProductBtn))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(scheduleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(movieBtn)))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(seatBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(theaterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(storageBtn)
                        .addGap(25, 25, 25))))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(employeeBtn)
                .addGap(66, 66, 66)
                .addComponent(reportBtn)
                .addGap(89, 89, 89))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scheduleBtn)
                                    .addComponent(movieBtn))
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(theaterBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sellProductBtn)
                            .addComponent(seatBtn)))
                    .addComponent(storageBtn))
                .addGap(48, 48, 48)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saleBtn)
                    .addComponent(reportBtn)
                    .addComponent(employeeBtn))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleBtnActionPerformed
        // TODO add your handling code here:

        new ScheduleView().setVisible(true);
        
    }//GEN-LAST:event_scheduleBtnActionPerformed

    private void theaterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theaterBtnActionPerformed
        // TODO add your handling code here:
        new TheaterMCView().setVisible(true);
    }//GEN-LAST:event_theaterBtnActionPerformed

    private void saleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleBtnActionPerformed
        // TODO add your handling code here:
        new TransactionHistoryView().setVisible(true);
    }//GEN-LAST:event_saleBtnActionPerformed

    private void seatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatBtnActionPerformed
        // TODO add your handling code here:
        SeatView.main(null);

    }//GEN-LAST:event_seatBtnActionPerformed

    private void storageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storageBtnActionPerformed
        // TODO add your handling code here:
        new StorageMCView().setVisible(true);
    }//GEN-LAST:event_storageBtnActionPerformed

    private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
        // TODO add your handling code here:
        EmployeeMCView.main(null);
    }//GEN-LAST:event_employeeBtnActionPerformed

    private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnActionPerformed
        // TODO add your handling code here:
        new ReportMCView().setVisible(true);
    }//GEN-LAST:event_reportBtnActionPerformed

    private void sellProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellProductBtnActionPerformed
        // TODO add your handling code here:
        new SellProductMCView().setVisible(true);
    }//GEN-LAST:event_sellProductBtnActionPerformed

    private void movieBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:    
        new MovieView().setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm(empIdM).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton employeeBtn;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton movieBtn;
    private javax.swing.JButton reportBtn;
    private javax.swing.JButton saleBtn;
    private javax.swing.JButton scheduleBtn;
    private javax.swing.JButton seatBtn;
    private javax.swing.JButton sellProductBtn;
    private javax.swing.JButton storageBtn;
    private javax.swing.JButton theaterBtn;
    // End of variables declaration//GEN-END:variables
}
