/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MCViews;

import MCControllers.EmployeeController;
import java.awt.Frame;
import keeptoo.Drag;

/**
 *
 * @author DELL
 */
public class mainForm extends javax.swing.JFrame {

    public static int empIdM;

    public int getEmpId() {
        return empIdM;
    }

    public void setEmpId(int empId) {
        this.empIdM = empId;
    }

    /**
     * Creates new form mainForm
     */
    public mainForm(int empId) {
        initComponents();
        empIdM = empId;
        if (new EmployeeController().Fetch("id= " + empIdM).get(0).getAccess() == 1) {
            scheduleBtn.setEnabled(false);
            theaterBtn.setEnabled(false);
            saleBtn.setEnabled(false);
            storageBtn.setEnabled(false);
            employeeBtn.setEnabled(false);
            movieBtn.setEnabled(false);
            reportBtn.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        scheduleBtn = new javax.swing.JButton();
        movieBtn = new javax.swing.JButton();
        theaterBtn = new javax.swing.JButton();
        saleBtn = new javax.swing.JButton();
        seatBtn = new javax.swing.JButton();
        storageBtn = new javax.swing.JButton();
        employeeBtn = new javax.swing.JButton();
        reportBtn = new javax.swing.JButton();
        sellProductBtn = new javax.swing.JButton();
        formLbl = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        minimizeBtn = new javax.swing.JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mega Cinema");
        setBackground(new java.awt.Color(252, 214, 112));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(620, 400));
        setMinimumSize(new java.awt.Dimension(620, 400));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(44, 130, 201));
        kGradientPanel2.setkStartColor(new java.awt.Color(242, 38, 19));
        kGradientPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel2MouseDragged(evt);
            }
        });
        kGradientPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel2MousePressed(evt);
            }
        });
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scheduleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/scheduleIcon64px.png"))); // NOI18N
        scheduleBtn.setText("Schedule");
        scheduleBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        scheduleBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        scheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(scheduleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        movieBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/movieIcon64px.png"))); // NOI18N
        movieBtn.setText("Movie");
        movieBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        movieBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        movieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(movieBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        theaterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/theaterIcon64px.png"))); // NOI18N
        theaterBtn.setText("Theater");
        theaterBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        theaterBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        theaterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                theaterBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(theaterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        saleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/transactionIcon64px.png"))); // NOI18N
        saleBtn.setText("Transaction");
        saleBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saleBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(saleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 97, -1));

        seatBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/seatIcon64px.png"))); // NOI18N
        seatBtn.setText("Ticket Sale");
        seatBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seatBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        seatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(seatBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        storageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/storageIcon64px.png"))); // NOI18N
        storageBtn.setText("Storage");
        storageBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        storageBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        storageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storageBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(storageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        employeeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/employeeIcon64px.png"))); // NOI18N
        employeeBtn.setText("Employee");
        employeeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        employeeBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        employeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(employeeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        reportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/reportIcon64px.png"))); // NOI18N
        reportBtn.setText("Report");
        reportBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reportBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(reportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        sellProductBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/sellProductIcon64px.png"))); // NOI18N
        sellProductBtn.setText("Product Sale");
        sellProductBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sellProductBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sellProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellProductBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(sellProductBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        formLbl.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        formLbl.setForeground(new java.awt.Color(255, 255, 255));
        formLbl.setText("MEGA CINEMA");
        kGradientPanel2.add(formLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        exitBtn.setBackground(new java.awt.Color(240, 52, 52));
        exitBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setBorder(null);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 20, 20));

        minimizeBtn.setBackground(new java.awt.Color(51, 153, 0));
        minimizeBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        minimizeBtn.setForeground(new java.awt.Color(255, 255, 255));
        minimizeBtn.setBorder(null);
        minimizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 20, 20));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sellProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellProductBtnActionPerformed
        // TODO add your handling code here:
        new SellProductMCView().setVisible(true);
    }//GEN-LAST:event_sellProductBtnActionPerformed

    private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnActionPerformed
        // TODO add your handling code here:
        new ReportMCView().setVisible(true);
    }//GEN-LAST:event_reportBtnActionPerformed

    private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
        // TODO add your handling code here:
        EmployeeMCView.main(null);
    }//GEN-LAST:event_employeeBtnActionPerformed

    private void storageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storageBtnActionPerformed
        // TODO add your handling code here:
        new StorageMCView().setVisible(true);
    }//GEN-LAST:event_storageBtnActionPerformed

    private void seatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatBtnActionPerformed
        // TODO add your handling code here:
        SeatView.main(null);
    }//GEN-LAST:event_seatBtnActionPerformed

    private void saleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleBtnActionPerformed
        // TODO add your handling code here:
        new TransactionHistoryView().setVisible(true);
    }//GEN-LAST:event_saleBtnActionPerformed

    private void theaterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_theaterBtnActionPerformed
        // TODO add your handling code here:
        new TheaterMCView().setVisible(true);
    }//GEN-LAST:event_theaterBtnActionPerformed

    private void movieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieBtnActionPerformed
        // TODO add your handling code here:
        new MovieView().setVisible(true);

    }//GEN-LAST:event_movieBtnActionPerformed

    private void scheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleBtnActionPerformed
        // TODO add your handling code here:

        new ScheduleView().setVisible(true);
    }//GEN-LAST:event_scheduleBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void minimizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtnActionPerformed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnActionPerformed

    private void kGradientPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel2MouseDragged
        // TODO add your handling code here:
        new Drag(kGradientPanel2).moveWindow(evt);
    }//GEN-LAST:event_kGradientPanel2MouseDragged

    private void kGradientPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel2MousePressed
        // TODO add your handling code here:
        new Drag(kGradientPanel2).onPress(evt);
    }//GEN-LAST:event_kGradientPanel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm(empIdM).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton employeeBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel formLbl;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JButton movieBtn;
    private javax.swing.JButton reportBtn;
    private javax.swing.JButton saleBtn;
    private javax.swing.JButton scheduleBtn;
    private javax.swing.JButton seatBtn;
    private javax.swing.JButton sellProductBtn;
    private javax.swing.JButton storageBtn;
    private javax.swing.JButton theaterBtn;
    // End of variables declaration//GEN-END:variables
}
