/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MCViews;

import MCControllers.MovieController;
import MCModels.Movie;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import keeptoo.Drag;

/**
 *
 * @author DELL
 */
public class MovieView extends javax.swing.JFrame {

    MovieController movieC = new MovieController();
    int act = 0;
    boolean tableRowClicked = false;
    boolean chooseImageClicked = false;
    String imagePath;
    String fileName = null;
    byte[] imageFile = null;

    /**
     * Creates new form MovieView
     */
    public MovieView() {
        initComponents();
        this.setDefaultLookAndFeelDecorated(true);
        this.pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addRBGroup = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        movieTable = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        modifyBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        movieNameTextField = new javax.swing.JTextField();
        nameText = new javax.swing.JLabel();
        durationText = new javax.swing.JLabel();
        movieDurTextField = new javax.swing.JTextField();
        availableRB = new javax.swing.JRadioButton();
        notAvailableRB = new javax.swing.JRadioButton();
        statusText = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        imageLbl = new javax.swing.JLabel();
        chooseImgBtn = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        movieFLbl = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        minuteLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movie Management");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(210, 77, 87));
        kGradientPanel1.setkStartColor(new java.awt.Color(34, 49, 63));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });

        movieTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        movieTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Duration", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        movieTable.setFocusable(false);
        movieTable.setGridColor(new java.awt.Color(255, 255, 255));
        movieTable.setOpaque(false);
        movieTable.setSelectionBackground(new java.awt.Color(150, 40, 27));
        movieTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        movieTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(movieTable);
        if (movieTable.getColumnModel().getColumnCount() > 0) {
            movieTable.getColumnModel().getColumn(0).setMinWidth(3);
            movieTable.getColumnModel().getColumn(0).setPreferredWidth(3);
            movieTable.getColumnModel().getColumn(2).setMinWidth(5);
            movieTable.getColumnModel().getColumn(2).setPreferredWidth(10);
            movieTable.getColumnModel().getColumn(3).setMinWidth(5);
            movieTable.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        addBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/addIcon32px.png"))); // NOI18N
        addBtn.setText("Add");
        addBtn.setBorder(null);
        addBtn.setMaximumSize(new java.awt.Dimension(115, 45));
        addBtn.setMinimumSize(new java.awt.Dimension(115, 45));
        addBtn.setOpaque(false);
        addBtn.setPreferredSize(new java.awt.Dimension(115, 45));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        modifyBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modifyBtn.setForeground(new java.awt.Color(255, 255, 255));
        modifyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/modifyIcon32px.png"))); // NOI18N
        modifyBtn.setText("Modify");
        modifyBtn.setToolTipText("");
        modifyBtn.setBorder(null);
        modifyBtn.setMaximumSize(new java.awt.Dimension(115, 45));
        modifyBtn.setMinimumSize(new java.awt.Dimension(115, 45));
        modifyBtn.setOpaque(false);
        modifyBtn.setPreferredSize(new java.awt.Dimension(115, 45));
        modifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/deleteIcon32px.png"))); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(null);
        deleteBtn.setMaximumSize(new java.awt.Dimension(115, 45));
        deleteBtn.setMinimumSize(new java.awt.Dimension(115, 45));
        deleteBtn.setOpaque(false);
        deleteBtn.setPreferredSize(new java.awt.Dimension(115, 45));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        movieNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        movieNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        movieNameTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        movieNameTextField.setOpaque(false);

        nameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameText.setForeground(new java.awt.Color(255, 255, 255));
        nameText.setText("Name");

        durationText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        durationText.setForeground(new java.awt.Color(255, 255, 255));
        durationText.setText("Duration");

        movieDurTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        movieDurTextField.setForeground(new java.awt.Color(255, 255, 255));
        movieDurTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        movieDurTextField.setOpaque(false);

        addRBGroup.add(availableRB);
        availableRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        availableRB.setForeground(new java.awt.Color(255, 255, 255));
        availableRB.setText("Available");
        availableRB.setOpaque(false);

        addRBGroup.add(notAvailableRB);
        notAvailableRB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notAvailableRB.setForeground(new java.awt.Color(255, 255, 255));
        notAvailableRB.setText("Not Available");
        notAvailableRB.setOpaque(false);

        statusText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statusText.setForeground(new java.awt.Color(255, 255, 255));
        statusText.setText("Status");

        saveBtn.setBackground(new java.awt.Color(210, 77, 87));
        saveBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/saveIcon32px.png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.setBorder(null);
        saveBtn.setMaximumSize(new java.awt.Dimension(115, 45));
        saveBtn.setMinimumSize(new java.awt.Dimension(115, 45));
        saveBtn.setOpaque(false);
        saveBtn.setPreferredSize(new java.awt.Dimension(115, 45));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        imageLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        chooseImgBtn.setBackground(new java.awt.Color(210, 77, 87));
        chooseImgBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chooseImgBtn.setForeground(new java.awt.Color(255, 255, 255));
        chooseImgBtn.setText("Choose Image ");
        chooseImgBtn.setBorder(null);
        chooseImgBtn.setOpaque(false);
        chooseImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseImgBtnActionPerformed(evt);
            }
        });

        searchTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchTextField.setForeground(new java.awt.Color(255, 255, 255));
        searchTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        searchTextField.setOpaque(false);

        searchBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MCImage/searchIcon32px.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setBorder(null);
        searchBtn.setMaximumSize(new java.awt.Dimension(115, 45));
        searchBtn.setMinimumSize(new java.awt.Dimension(115, 45));
        searchBtn.setOpaque(false);
        searchBtn.setPreferredSize(new java.awt.Dimension(115, 45));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        movieFLbl.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        movieFLbl.setForeground(new java.awt.Color(255, 255, 255));
        movieFLbl.setText("Movie Management");

        exitBtn.setBackground(new java.awt.Color(240, 52, 52));
        exitBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Back");
        exitBtn.setBorder(null);
        exitBtn.setMaximumSize(new java.awt.Dimension(30, 15));
        exitBtn.setMinimumSize(new java.awt.Dimension(30, 15));
        exitBtn.setPreferredSize(new java.awt.Dimension(30, 15));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        minuteLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        minuteLbl.setForeground(new java.awt.Color(255, 255, 255));
        minuteLbl.setText("minutes");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                            .addComponent(nameText)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(movieNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(durationText)
                                                .addComponent(statusText))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                    .addComponent(availableRB)
                                                    .addGap(36, 36, 36)
                                                    .addComponent(notAvailableRB))
                                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                    .addComponent(movieDurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(minuteLbl)))
                                            .addGap(47, 47, 47)))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(imageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(chooseImgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(movieFLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 650, Short.MAX_VALUE)
                                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(modifyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                    .addGap(419, 419, 419)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(movieFLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(searchTextField)
                        .addGap(6, 6, 6)))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText)
                    .addComponent(movieNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durationText)
                    .addComponent(movieDurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuteLbl))
                .addGap(17, 17, 17)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusText)
                    .addComponent(availableRB)
                    .addComponent(notAvailableRB))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(chooseImgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void modifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBtnActionPerformed
        // TODO add your handling code here:
        if (tableRowClicked == true) {
            movieNameTextField.setEditable(true);
            movieDurTextField.setEditable(true);

            movieNameTextField.setText(movieTable.getValueAt(movieTable.getSelectedRow(), 1).toString());
            movieDurTextField.setText(movieTable.getValueAt(movieTable.getSelectedRow(), 2).toString());

            act = 2;  //tell save button to save info modify
        } else {
            JOptionPane.showMessageDialog(null, "Please select a movie");
        }
    }//GEN-LAST:event_modifyBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:

        if (tableRowClicked == true) {
            int id = (int) movieTable.getValueAt(movieTable.getSelectedRow(), 0);
            int res = movieC.delete(id);
            int check = JOptionPane.showConfirmDialog(jScrollPane1, "Are you sure delete this movie?", "Delete", JOptionPane.YES_NO_OPTION);
            if (check == JOptionPane.YES_OPTION) {
                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Deleted successfully");
                } else if (res == 0) {
                    JOptionPane.showMessageDialog(null, "Unable to delete");
                }

                refresh();
                act = 0;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a movie");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        //JLayeredPane layeredP = (JLayeredPane) LayeredPane.getLayer();
        movieNameTextField.setEditable(true);
        movieDurTextField.setEditable(true);
        movieNameTextField.setText("");
        movieDurTextField.setText("");
        imageLbl.setIcon(null);

        act = 1;  //tell save button to act add
    }//GEN-LAST:event_addBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if (act == 1) //save add info
        {
            int status;
            if (availableRB.isSelected() == true) {
                status = 1;
            } else {
                status = 2;
            }

            Movie movie = new Movie();

            movie.setName(movieNameTextField.getText());
            movie.setDuration(Integer.parseInt(movieDurTextField.getText()));
            movie.setStatus(status);

            if (chooseImageClicked == true) {
                movie.setImage(imageFile);
            }

            int res = movieC.add(movie);
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Saved - add new info");
            } else {
                JOptionPane.showMessageDialog(null, "Unable to save");
            }
            refresh();
            act = 0;
            movieNameTextField.setEditable(false);
            movieDurTextField.setEditable(false);
            chooseImageClicked = false;

        } else if (act == 2) //save modify info
        {
            int id = (int) movieTable.getValueAt(movieTable.getSelectedRow(), 0);
            System.out.println("id: " + id);
            String name = movieNameTextField.getText();
            int dur = Integer.parseInt(movieDurTextField.getText());
            int status;
            if (availableRB.isSelected() == true) {
                status = 1;
            } else {
                status = 2;
            }

            Movie movie = new Movie();
            movie.setId(id);
            movie.setName(name);
            movie.setDuration(dur);
            movie.setStatus(status);

            if (chooseImageClicked == true) {
                movie.setImage(imageFile);
            } else {
                movie.setImage(movieC.select("movieId=" + movieTable.getValueAt(movieTable.getSelectedRow(), 0)).get(0).getImage());
            }

            int res = movieC.modify(movie);
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Saved info changed");
            } else {
                JOptionPane.showMessageDialog(null, "Unable to save");
            }

            refresh();
            act = 0;
            movieNameTextField.setEditable(false);
            movieDurTextField.setEditable(false);
            chooseImageClicked = false;
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:

//        Object rowData[] = new Object[4];
//        Object[][] movieData = movieC.SelectAll();
//        int length = (int) movieData[0][0];
        DefaultTableModel model = (DefaultTableModel) movieTable.getModel();

        movieNameTextField.setEditable(false);
        movieDurTextField.setEditable(false);

//        Object rowData[] = new Object[4];
//        Object[][] movieData = movieC.SelectAll();
//        int length = (int) movieData[0][0];
        List<Movie> movieList = movieC.selectAll();
        Object rowData[] = new Object[4];

        for (int i = 0; i < movieList.size(); i++) {
            rowData[0] = movieList.get(i).getId();
            rowData[1] = movieList.get(i).getName();
            rowData[2] = movieList.get(i).getDuration();
            rowData[3] = movieList.get(i).getStatus();
            model.addRow(rowData);
        }
        imageLbl.setIcon(null);

        movieTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                tableRowClicked = true;
                movieNameTextField.setEditable(false);
                movieDurTextField.setEditable(false);
                //imageLbl = movieC.select("movieId="+movieTable.getValueAt(movieTable.getSelectedRow(), 0)).get(0).getImage();
                Image img = null;
                img = convertByteToImage(movieC.select("movieId=" + movieTable.getValueAt(movieTable.getSelectedRow(), 0)).get(0).getImage());
                if (img != null) {
                    ImageIcon imageIcon = new ImageIcon(img.getScaledInstance(imageLbl.getWidth(), imageLbl.getHeight(), Image.SCALE_SMOOTH));
                    imageLbl.setIcon(imageIcon);
                } else {
                    imageLbl.setIcon(null);
                }
            }
        });


    }//GEN-LAST:event_formComponentShown

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        movieTable.clearSelection();

        DefaultTableModel model = (DefaultTableModel) movieTable.getModel();

        model.setRowCount(0);   //clear data table

        List<Movie> movieList = movieC.select("movieName like '%" + searchTextField.getText() + "%'");
        Object rowData[] = new Object[4];

        for (int i = 0; i < movieList.size(); i++) {
            rowData[0] = movieList.get(i).getId();
            rowData[1] = movieList.get(i).getName();
            rowData[2] = movieList.get(i).getDuration();
            rowData[3] = movieList.get(i).getStatus();
            model.addRow(rowData);
        }

        movieTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                movieNameTextField.setEditable(false);
                movieDurTextField.setEditable(false);

                Image img = null;
                img = convertByteToImage(movieC.select("movieId=" + movieTable.getValueAt(movieTable.getSelectedRow(), 0)).get(0).getImage());
                if (img != null) {
                    ImageIcon imageIcon = new ImageIcon(img.getScaledInstance(imageLbl.getWidth(), imageLbl.getHeight(), Image.SCALE_SMOOTH));
                    imageLbl.setIcon(imageIcon);
                } else {
                    imageLbl.setIcon(null);
                }
            }
        });
    }//GEN-LAST:event_searchBtnActionPerformed

    private void chooseImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseImgBtnActionPerformed
        // TODO add your handling code here:
        chooseImageClicked = true;
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg", "gif", "png");
        fileChooser.addChoosableFileFilter(filter);

        fileChooser.showOpenDialog(null);
        File f = fileChooser.getSelectedFile();
        fileName = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(fileName).getImage().getScaledInstance(imageLbl.getWidth(), imageLbl.getHeight(), Image.SCALE_SMOOTH));
        imageLbl.setIcon(imageIcon);
        try {
            File image = new File(fileName);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
            }
            imageFile = bos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_chooseImgBtnActionPerformed


    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        // TODO add your handling code here:
        new Drag(kGradientPanel1).onPress(evt);

    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        // TODO add your handling code here:
        new Drag(kGradientPanel1).moveWindow(evt);
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    public void refresh() {
        // TODO add your handling code here:

        movieTable.clearSelection();

        DefaultTableModel model = (DefaultTableModel) movieTable.getModel();

        model.setRowCount(0);   //clear data table

        //add info to table
        List<Movie> movieList = movieC.selectAll();
        Object rowData[] = new Object[4];

        for (int i = 0; i < movieList.size(); i++) {
            rowData[0] = movieList.get(i).getId();
            rowData[1] = movieList.get(i).getName();
            rowData[2] = movieList.get(i).getDuration();
            rowData[3] = movieList.get(i).getStatus();
            model.addRow(rowData);
        }

        movieNameTextField.setEditable(false);
        movieDurTextField.setEditable(false);
        tableRowClicked = false;

        movieTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {

                movieNameTextField.setEditable(false);
                movieDurTextField.setEditable(false);

                Image img = null;
                img = convertByteToImage(movieC.select("movieId=" + movieTable.getValueAt(movieTable.getSelectedRow(), 0)).get(0).getImage());
                if (img != null) {
                    ImageIcon imageIcon = new ImageIcon(img.getScaledInstance(imageLbl.getWidth(), imageLbl.getHeight(), Image.SCALE_SMOOTH));
                    imageLbl.setIcon(imageIcon);
                } else {
                    imageLbl.setIcon(null);
                }
            }
        });
    }

    public Image convertByteToImage(byte[] img) {
        BufferedImage image = null;
        if (img != null) {
            InputStream inputStream = new ByteArrayInputStream(img);

            try {
                image = ImageIO.read(inputStream);
            } catch (IOException ex) {
                Logger.getLogger(MovieView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return image;
    }

    public ImageIcon ResizeImage(String imgPath) {
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(imageLbl.getWidth(), imageLbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    System.out.println("Run");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.ButtonGroup addRBGroup;
    private javax.swing.JRadioButton availableRB;
    private javax.swing.JButton chooseImgBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel durationText;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel minuteLbl;
    private javax.swing.JButton modifyBtn;
    private javax.swing.JTextField movieDurTextField;
    private javax.swing.JLabel movieFLbl;
    private javax.swing.JTextField movieNameTextField;
    private javax.swing.JTable movieTable;
    private javax.swing.JLabel nameText;
    private javax.swing.JRadioButton notAvailableRB;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel statusText;
    // End of variables declaration//GEN-END:variables
}
